### ISSUE TITLE
Terraform v0.12 breaks exporting VAULT_ADDR from terraform output. 

### ISSUE THREAD

**Issue by arvindamirtaa** [alexandarp/terraform-gce-vault#1]
The following line on the script is no longer supported on Terraform V0.12. 

export VAULT_ADDR="$(terraform output -module=vault vault_addr)"

Produces the following error 

`Error: Unsupported option

The -module option is no longer supported since Terraform 0.12, because now
only root outputs are persisted in the state.`

Any idea how to go about this now?

**Comment by alexandarp** [comment]
Thanks for reporting this.

It has been addressed in #2
